config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }

  root 'conversations#index'

  resources :users

  resources :conversations do
    member do
      post :reply
    end
  end

  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :restore
    end
  end

  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :mark_as_read
    end
  end

  resources :messages
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  acts_as_messageable

  def mailboxer_email(_object)
    nil
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  rescue_from ActiveRecord::RecordNotFound do
    flash[:warning] = 'Resource not found.'
    redirect_back_or root_path
  end

  def redirect_back_or(path)
    redirect_to request.referer || path
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!
  before_action :mailbox
  before_action :conversation, except: [:index]
  before_action :box, only: [:index]
  before_action :unread_msg

  def index
    if @box.eql? 'inbox'
      @conversations = @mailbox.inbox
    elsif @box.eql? 'unread'
      @conversations = @mailbox.inbox.unread(current_user)
    elsif @box.eql? 'sent'
      @conversations = @mailbox.sentbox
    else
      @conversations = @mailbox.trash
    end
    @conversations = @conversations.paginate(page: params[:page], per_page: 10)

    flash[:danger] = "You have #{@unread_count} unread messages" if @unread_count > 0
  end

  def show; end

  def new
    @recipients = User.all - [current_user]
  end

  def create
    recipient = User.find(params[:user_id])
    receipt   = current_user.send_message(recipient, params[:body], params[:subject])
    redirect_to conversation_path receipt.conversation
  end

  def reply
    current_user.reply_to_conversation(@conversation, params[:body])
    flash[:success] = 'Reply sent'
    redirect_to conversation_path(@conversation)
  end

  def destroy
    @conversation.move_to_trash(current_user)
    flash[:success] = 'The conversation was moved to trash.'
    redirect_to conversations_path
  end

  def restore
    @conversation.untrash(current_user)
    flash[:success] = 'The conversation was restored.'
    redirect_to conversations_path
  end

  def mark_as_read
    @conversation.mark_as_read(current_user)
    flash[:success] = 'The conversation was marked as read.'
    redirect_to conversations_path
  end

  private

  def mailbox
    @mailbox ||= current_user.mailbox
    @unread_count = current_user.unread_inbox_count
  end

  def conversation
    @conversation ||= @mailbox.conversations.find(params[:id])
  end

  def box
    if params[:box].blank? || !%w[inbox sent trash unread].include?(params[:box])
      params[:box] = 'inbox'
    end
    @box = params[:box]
  end

  def unread_msg
    @unread = current_user.mailbox.conversations.select do |c|
       c if c.is_unread?(current_user)
    end
    @unread
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!

  def new
    @chosen_recipient = User.find_by(id: params[:to].to_i) if params[:to]
  end

  def create
    recipients = User.where(id: params['recipients'])
    conversation = current_user
                   .send_message(recipients, params[:message][:body],
                                 params[:message][:subject]).conversation
    flash[:success] = 'Message has been sent!'
    redirect_to conversation_path(conversation)
  end
end

app/controllers/registrations_controller.rb
# add name field ato resistration and user at all
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:name, :email,
                                 :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation, :current_password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    if current_user.admin?
      @users = User.order('created_at DESC').paginate(page: params[:page], per_page: 30)
    else
      redirect_to root_path
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_header(text)
    content_for(:page_header) { text.to_s }
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
  def mailbox_section(title, current_box, opts = {})
    opts[:class] = opts.fetch(:class, '')
    opts[:class] += ' active' if title.downcase == current_box
    content_tag :li, link_to(title.capitalize, conversations_path(box: title.downcase)), opts
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
  def recipients_options(chosen_recipient = nil)
    s = ''
    User.all.each do |user|
      next if user.id == current_user.id
      s << "<option value='#{user.id}' #{'selected' if user == chosen_recipient}> #{user.name}</option>"
    end
    s.html_safe
  end
end

app/views/conversations/_conversation.html.erb
<li class="list-group-item clearfix">
  <%= link_to conversation.subject, conversation_path(conversation) %>

  <div class="btn-group-vertical pull-right">
    <% if conversation.is_trashed?(current_user) %>
      <%= link_to 'Restore', restore_conversation_path(conversation), class: 'btn btn-xs btn-info', method: :post %>
    <% else %>
      <%= link_to 'Move to trash', conversation_path(conversation), class: 'btn btn-xs btn-danger', method: :delete,
        data: {confirm: 'Are you sure?'} %>
      <% if conversation.is_unread?(current_user) %>
        <%= link_to 'Mark as read', mark_as_read_conversation_path(conversation),
        class: 'btn btn-xs btn-info', method: :post %>
      <% end %>
    <% end %>
  </div>

  <p><%= render 'participants', conversation: conversation %></p>

  <p><%= conversation.last_message.body %>
    <small>(<span class="text-muted"><%= conversation.last_message.created_at.strftime("%-d %B %Y, %H:%M:%S") %></span>)</small>
  </p>
</li>

app/views/conversations/_participants.html.erb
<% conversation.participants.each do |participant| %>
  <% unless participant == current_user %>
    <%= participant.name %>
  <% end %>
<% end %>

app/views/conversations/index.html.erb
<% page_header 'Your conversations' %>

<div class="row">
  <p><%= link_to 'Start conversation', new_message_path, class: 'btn btn-primary' %>
    <%= link_to 'Search for new email', '#', onclick: 'location.reload(true);', class: 'btn btn-success' %>
    <button class="btn btn-primary" type="button">
      Unread Messages <span class="badge"><%= "#{@unread_count}" %></span>
    </button>
  </p>

  <div class="col-sm-9">
    <ul class="nav nav-tabs nav-justified">
      <%= mailbox_section 'inbox', @box %>
      <%= mailbox_section 'sent', @box %>
      <%= mailbox_section 'unread', @box %>
      <%= mailbox_section 'trash', @box %>
    </ul>
  </div>

  <div class="col-sm-9">
    <ul class="list-group">
      <%= render partial: 'conversations/conversation', collection: @conversations %>
    </ul>

    <%= will_paginate %>
  </div>
</div>

app/views/conversations/new.html.erb
<h1> New conversation </h1>

<%= form_tag conversations_path, method: :post do %>
  <div>
    <%= select_tag :user_id, options_from_collection_for_select(@recipients, :id, :name) %>
  </div>

  <div>
    <%= text_field_tag :subject, nil, placeholder: "Subject" %>
  </div>

  <div>
    <%= text_area_tag :body, nil, placeholder: "Your message" %>
  </div>
  <%= submit_tag 'Send' %>
<% end %>

app/views/conversations/show.html.erb
<% page_header "Conversation" %>

<p>Chatting with
  <%= render 'conversations/participants', conversation: @conversation %>
</p>

<div class="panel panel-default">
  <div class="panel-heading">Subject: <%= @conversation.subject %></div>

  <div class="panel-body">
    <div class="messages">
      <% @conversation.receipts_for(current_user).each do |receipt| %>
        <div class="media">
          <% message = receipt.message %>

          <div class="media-body">
            <h6 class="media-heading">
              <%= message.sender.name %> says at <%= message.created_at.strftime("%-d %B %Y, %H:%M:%S") %>:</h6>
            <%= message.body %>
            <hr>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<%= form_tag reply_conversation_path(@conversation), method: :post do %>
  <div class="form-group">
    <%= text_area_tag 'body', nil, cols: 3, class: 'form-control', placeholder: 'Type something...', required: true %>
  </div>
  <%= submit_tag "Send Message", class: 'btn btn-primary' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTicketsUa</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %> alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%= value %>
        </div>
      <% end %>
      
      <nav class="navbar">
        <div class="container">
          <ol class="breadcrumb">
            <% if user_signed_in? %>
              <li><%= link_to 'Messenger', root_path %></li>
              <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
              <li><%= link_to 'Your Conversations', conversations_path %></li>
              <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to 'Log In', new_user_session_path %></li>
            <% end %>
            <% if current_user.admin == true %>
              <li> <%= link_to 'List of Users', users_path%> </li>
            <% end %>
          </ol>
        </div>
      </nav>
      
      <div class="page-header">
        <h1><%= yield :page_header %></h1>
      </div>

      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/new.html.erb
<% page_header "Start Conversation" %>

<%= form_tag messages_path, method: :post do %>
  <div class="form-group">
    <%= label_tag 'message[subject]', 'Subject' %>
    <%= text_field_tag 'message[subject]', nil, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= label_tag 'message[body]', 'Message' %>
    <%= text_area_tag 'message[body]', nil, cols: 3, class: 'form-control', required: true %>
  </div>
  
  <div>
    <%= select_tag 'recipients', recipients_options(@chosen_recipient), multiple: false, title: "Choose one of the following...", class: 'form-control' %>
  </div>
  
  <%= submit_tag 'Send', class: 'btn btn-primary' %>
<% end %>

app/views/users/index.html.erb
<% page_header "Users" %>

<%= will_paginate %>

<ul>
  <% @users.each do |user| %>
    <li>
      <strong><%= user.name %></strong>
      <% unless current_user == user %>
        <%= link_to "Destroy", user_path(user), method: :delete, data: { confirm: "You sure?" } %>
      <% end %>
    </li>
  <% end %>
</ul>

<%= will_paginate %>